set(PHH_JSONCPP_FOUND false)

find_package(JsonCpp CONFIG QUIET)
if(NOT JsonCpp_FOUND)
    find_package(jsoncpp CONFIG QUIET)
endif()
if(NOT JsonCpp_FOUND AND NOT jsoncpp_FOUND)
    find_package(Jsoncpp CONFIG QUIET)
endif()
if(NOT JsonCpp_FOUND AND NOT jsoncpp_FOUND AND NOT Jsoncpp_FOUND)
    find_package(PkgConfig QUIET)
    if(PKG_CONFIG_FOUND)
        pkg_check_modules(JSONCPP jsoncpp)
        if(JSONCPP_FOUND)
            set(JsonCpp_FOUND TRUE)
        endif()
    endif()
endif()

if(JsonCpp_FOUND OR jsoncpp_FOUND OR Jsoncpp_FOUND OR JSONCPP_FOUND)
    set(PHH_JSONCPP_FOUND true)
    message(STATUS "JsonCpp found")
    string(APPEND PHH_FEATURES_LIST "- JsonCpp              : found\n")
else()
    string(APPEND PHH_FEATURES_LIST "- JsonCpp              : not found\n")
endif()

